### PR TITLE
butterfly, fish, sawblade models (for rails)

### PR DESCRIPTION
**Pull request by Jigoku**

### CODE REVIEW

**Review by cloudziq — COMMENTED** [review]
noticed that sawblade obj.cfg have `objspec * spec.png` and few lines later `mdlspec 100` which overwrites objspec *

I think this command is used only for specscale,  and specmap itself should be defined in model mask file

**Review by cloudziq — COMMENTED** [review]
above message sent two times due to network error :/  deleted

**Comment by Jigoku** [comment]
Overlooked that, model seems to look better with mdlspec, i'll remove the specmap

**Comment by qreeves** [comment]
Can I get you to rename `LICENSE` to `license.txt` or `readme.txt` for consistency with the rest of the project please?

**Comment by Jigoku** [comment]
Yep, sorry, that's a habit of mine.

**Comment by Jigoku** [comment]
Done

**Pull request merged**
